import { describe, expect, it } from 'vitest';
import { configuration, sampleItem, time } from './overviewRuntimeFixtures.js';
import { formatRuntimeNumber, runtimePresentation, receivedAge, captionText, presentationAge } from './overviewRuntimePresentation.js';
describe('B3 values and four-state separation',()=>{
 it.each([0,-0,12.123456789,-99,1e9,1e-7,Number.MAX_VALUE])('formats finite %s without mutation',value=>{expect(formatRuntimeNumber(value)).not.toBeNull();expect(formatRuntimeNumber(value)!.length).toBeLessThanOrEqual(20);});
 it.each([NaN,Infinity,-Infinity,true,false,'0',null,undefined])('rejects coercion/nonfinite %j',value=>expect(formatRuntimeNumber(value)).toBeNull());
 it('format boundaries and negative zero',()=>{expect(formatRuntimeNumber(-0)).toBe('0');expect(formatRuntimeNumber(12.123456789)).toBe('12.123457');expect(formatRuntimeNumber(1e9)).toContain('e+9');expect(formatRuntimeNumber(1e-7)).toContain('e-7');expect(formatRuntimeNumber(1e-6)).toBe('0.000001');});
 it.each([0,true,false])('preserves valid %s and unit',value=>{const f=configuration(1,typeof value==='boolean'?'STATUS_LIGHT':'NUMERIC_LABEL');const p=runtimePresentation(f.element,f.resolution,sampleItem(1,value),'Connected');expect(p.value).toBe(value);expect(p.text).toBe(typeof value==='boolean'?value?'TRUE':'FALSE':'0');expect(p.unit).toBe(typeof value==='number'?'bar':'');});
 it.each(['GOOD','UNCERTAIN','STALE','BAD','DISCONNECTED'] as const)('renders quality %s and explicit last-good',quality=>{const f=configuration(),item=sampleItem(1,4,quality),before=JSON.stringify(item);const p=runtimePresentation(f.element,f.resolution,item,'Connected');expect(p.quality).toBe(quality);expect(p.historical).toBe(['BAD','DISCONNECTED'].includes(quality));if(p.historical){expect(p.label).toBe('Last good');expect(p.timestamp).toBe(time);}expect(JSON.stringify(item)).toBe(before);});
 it('UNCERTAIN no sample never fabricates false/zero, BAD without last-good stays empty',()=>{const f=configuration(),item=sampleItem();Object.assign(item.sample!,{value:null,hasValue:false,quality:'UNCERTAIN',lastGoodValue:null,lastGoodReceiveTimestamp:null});item.availability='NO_SAMPLE';expect(runtimePresentation(f.element,f.resolution,item,'Connected')).toMatchObject({text:'—',quality:'UNCERTAIN'});item.sample!.quality='BAD';expect(runtimePresentation(f.element,f.resolution,item,'Connected').value).toBeNull();});
 it.each(['DEFINITION_MISSING','DEFINITION_DISABLED','UNCONFIGURED','MAPPING_DISABLED','DEVICE_MISSING','DEVICE_DISABLED','UNSUPPORTED','INCOMPATIBLE','NO_SAMPLE'] as const)('separates availability %s from Binding and quality',availability=>{const f=configuration(),item={...sampleItem(),availability};const p=runtimePresentation(f.element,f.resolution,item,'Connected');expect(p.historical).toBe(true);expect(p.quality).toBe('GOOD');expect(f.resolution.status).toBe('BOUND');});
 it.each(['Connecting','Reconnecting','Resynchronizing','Offline','Error','Disposed'] as const)('transport %s does not rewrite canonical GOOD',transport=>{const f=configuration(),item=sampleItem();expect(runtimePresentation(f.element,f.resolution,item,transport)).toMatchObject({quality:'GOOD',cached:true});expect(item.sample!.quality).toBe('GOOD');});
 it('String stays unsupported, caption never becomes process text',()=>{const f=configuration(1,'TEXT_LABEL');f.element.style.text='not a process sample';const p=runtimePresentation(f.element,f.resolution,undefined,'Connected');expect(p).toMatchObject({text:'—',availability:'Unsupported producer'});expect(f.resolution.status).toBe('BOUND');});
 it('rejects malformed process samples at display boundary',()=>{const f=configuration(),item=sampleItem();item.sample!.value=NaN;expect(runtimePresentation(f.element,f.resolution,item,'Connected')).toMatchObject({text:'—',tone:'bad'});});
 it('false lamp differs from no sample, BAD and Device disconnect',()=>{const f=configuration(1,'STATUS_LIGHT');expect(runtimePresentation(f.element,f.resolution,sampleItem(1,false),'Connected').lamp).toBe('false');for(const quality of ['BAD','DISCONNECTED'] as const)expect(runtimePresentation(f.element,f.resolution,sampleItem(1,false,quality),'Connected').lamp).toBe('unavailable');});
 it('uses timestamp age accurately, rejects invalid/future time, bounds Unicode captions',()=>{expect(receivedAge(time,Date.parse(time)+12000)).toBe('12s since receive');expect(receivedAge(time,Date.parse(time)-1)).toContain('clock skew');expect(receivedAge(null,0)).toContain('No receive');expect(receivedAge('bad',0)).toContain('Invalid');expect(captionText('🙂'.repeat(300))).toHaveLength(241);});
 it('paused age never displays a frozen elapsed duration as current',()=>{for(const state of ['Offline','Error','Disposed'] as const)expect(presentationAge(time,Date.parse(time)+10000,state)).toBe(`Received at ${time} (age paused)`);});
 it('String-bound Badge is unsupported rather than missing or fabricated process text',()=>{const f=configuration(1,'VALUE_BADGE');f.definition.dataType='String';f.element.binding.dataType='String';const p=runtimePresentation(f.element,{...f.resolution,definition:f.definition},undefined,'Connected');expect(p).toMatchObject({binding:'BOUND',text:'—',availability:'Unsupported producer',unit:''});});

});
