import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { configuration,harness,settle,sampleItem,id } from './overviewRuntimeFixtures.js';
import { OverviewRecoveryBudget } from './overviewTagClientAdapter.js';
const cases:ReturnType<typeof harness>[]=[];function setup(){const f=harness();cases.push(f);return f;}
beforeEach(()=>{vi.useFakeTimers();vi.spyOn(Math,'random').mockReturnValue(.5);});afterEach(()=>{cases.splice(0).forEach(f=>f.adapter.stop());vi.useRealTimers();vi.restoreAllMocks();});
describe('B3 approved headless recovery integration',()=>{
 it('short reconnect retains labeled canonical data and resumes without another Snapshot',async()=>{const f=setup();f.adapter.activate('p',configuration().selection);await settle();f.accept();f.delta('cursor-0','cursor-1');await vi.advanceTimersByTimeAsync(200);f.socket().onclose?.();expect(f.store.getStatus().transport).toBe('Reconnecting');expect(f.store.getItem(id())!.sample!.quality).toBe('GOOD');await vi.advanceTimersByTimeAsync(250);f.accept();expect(f.io.snapshot).toHaveBeenCalledTimes(1);expect(f.socket().sent[0].cursor).toBe('cursor-1');});
 it.each(['gap','resync','epoch','selection','protocol','overflow'])('%s clears old continuity and resnapshots',async cause=>{const f=setup();f.adapter.activate('p',configuration().selection);await settle();f.accept();if(cause==='resync')f.socket().receive({protocolVersion:1,type:'resync-required',reason:'REPLAY_EXPIRED'});else if(cause==='overflow')f.socket().onmessage?.({data:'x'.repeat(65537)});else f.socket().receive({...f.context(),type:'checkpoint',fromExclusive:cause==='gap'?'wrong':'cursor-0',toInclusive:'cursor-1',updates:[],...(cause==='epoch'?{serverEpoch:id(990)}:cause==='selection'?{selectionKey:'wrong'}:cause==='protocol'?{protocolVersion:99}:{})});expect(f.store.getStatus().transport).toBe('Resynchronizing');expect(f.store.size).toBe(0);await vi.advanceTimersByTimeAsync(250);expect(f.io.snapshot).toHaveBeenCalledTimes(2);});
 it('Server restart receives new epoch through fresh Snapshot',async()=>{const f=setup();f.adapter.activate('p',configuration().selection);await settle();f.accept();f.restart();f.socket().receive({protocolVersion:1,type:'resync-required'});await vi.advanceTimersByTimeAsync(250);f.accept();expect(f.store.getStatus().transport).toBe('Connected');expect(f.io.snapshot).toHaveBeenCalledTimes(2);});
 it.each(['SNAPSHOT_HTTP_400','SNAPSHOT_HTTP_403','SNAPSHOT_HTTP_413','SNAPSHOT_TOO_LARGE'])('permanent %s is visible, no retry storm',async message=>{const f=setup();vi.mocked(f.io.snapshot).mockRejectedValue(Error(message));f.adapter.activate('p',configuration().selection);await settle();expect(f.store.getStatus().transport).toBe('Error');expect(f.store.getStatus().message).toContain(message);expect(f.io.socket).not.toHaveBeenCalled();expect(vi.getTimerCount()).toBe(0);});
 it('limits automatic retries to five in rolling 60s; manual retry is throttled and does not reset budget',async()=>{const f=setup();vi.mocked(f.io.snapshot).mockRejectedValue(Error('server unavailable'));f.adapter.activate('p',configuration().selection);await settle();await vi.advanceTimersByTimeAsync(10000);expect(f.io.snapshot).toHaveBeenCalledTimes(6);expect(f.store.getStatus().transport).toBe('Error');expect(vi.getTimerCount()).toBe(0);expect(f.adapter.retry()).toBe(true);expect(f.adapter.retry()).toBe(false);await settle();expect(f.io.snapshot).toHaveBeenCalledTimes(7);expect(f.store.getStatus().transport).toBe('Error');});
 it('rolling expiry and reset require the documented stable-session duration',()=>{const b=new OverviewRecoveryBudget();for(let i=0;i<5;i++)expect(b.take(i)).toBe(true);expect(b.take(10)).toBe(false);b.resetAfterStableSession(59999);expect(b.take(11)).toBe(false);b.resetAfterStableSession(60000);expect(b.take(12)).toBe(true);const c=new OverviewRecoveryBudget();for(let i=0;i<5;i++)c.take(i);expect(c.take(60001)).toBe(true);});
 it('generic browser WS failure is not guessed to be Origin rejection',async()=>{const f=setup();f.adapter.activate('p',configuration().selection);await settle();f.accept();f.socket().onerror?.();expect(f.store.getStatus().message).not.toMatch(/Origin rejection|403/);});
 it('View re-entry does not erase the automatic recovery window',async()=>{const f=setup();vi.mocked(f.io.snapshot).mockRejectedValue(Error('down'));f.adapter.activate('p',configuration().selection);await settle();await vi.advanceTimersByTimeAsync(10000);expect(f.io.snapshot).toHaveBeenCalledTimes(6);f.adapter.stop();f.adapter.activate('p',configuration().selection);await settle();await vi.advanceTimersByTimeAsync(5000);expect(f.io.snapshot).toHaveBeenCalledTimes(7);expect(f.store.getStatus().transport).toBe('Error');});

});
