import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { readFileSync } from 'node:fs';
import { configuration, harness, settle, sampleItem, id } from './overviewRuntimeFixtures.js';
import { beginOverviewEdit, cancelOverviewEdit, finishOverviewSave } from './overviewState.js';
import { runtimeViewAllowed } from './overviewRuntimeSelection.js';
const cases:ReturnType<typeof harness>[]=[];function setup(){const f=harness();cases.push(f);return f;}
beforeEach(()=>{vi.useFakeTimers();vi.spyOn(Math,'random').mockReturnValue(.5);});afterEach(()=>{cases.splice(0).forEach(f=>f.adapter.stop());vi.useRealTimers();vi.restoreAllMocks();});
describe('B3 active View / Page session lifecycle',()=>{
 it('does not start at construction; validated Snapshot appears before subscription',async()=>{const f=setup();expect(f.io.snapshot).not.toHaveBeenCalled();f.adapter.activate('page',configuration().selection);await settle();expect(f.store.getItem(id())?.availability).toBe('NO_SAMPLE');expect(f.store.getStatus().transport).toBe('Connecting');expect(f.socket().sent).toEqual([]);f.accept();expect(f.store.getStatus().transport).toBe('Connected');expect(f.store.getStatus().message).toContain('catch-up is not confirmed');});
 it('StrictMode-style setup/cleanup/setup opens only the surviving session',async()=>{const f=setup(),s=configuration().selection;f.adapter.activate('page',s);f.adapter.stop();f.adapter.activate('page',s);await settle();expect(f.io.snapshot).toHaveBeenCalledTimes(1);expect(f.io.socket).toHaveBeenCalledTimes(1);});
 it('old Page snapshot cannot create a socket or update the new Page',async()=>{const f=setup();let resolve!:(x:unknown)=>void;const original=f.io.snapshot;vi.mocked(f.io.snapshot).mockImplementationOnce(()=>new Promise(r=>{resolve=r;}));f.adapter.activate('old',configuration().selection);await settle();f.adapter.activate('new',configuration(2).selection);await settle();resolve(await original(configuration().selection.sources,new AbortController().signal));await settle();expect(f.io.socket).toHaveBeenCalledTimes(1);expect(f.store.getStatus().pageId).toBe('new');expect(f.store.getItem(id())).toBeUndefined();expect(f.store.getItem(id(2))).toBeDefined();});
 it('old socket callbacks and scheduled publications cannot update a replacement',async()=>{const f=setup();f.adapter.activate('old',configuration().selection);await settle();f.accept();const late=f.socket().onmessage!,context=f.context();f.delta('cursor-0','cursor-1');f.adapter.activate('new',configuration(2).selection);await settle();late({data:JSON.stringify({...context,type:'checkpoint',fromExclusive:'cursor-1',toInclusive:'bad',updates:[]})});await vi.advanceTimersByTimeAsync(500);expect(f.store.getStatus().pageId).toBe('new');expect(f.store.getItem(id())).toBeUndefined();});
 it('enter Edit/inactive/close cleanup sends unsubscribe and fences all timers',async()=>{const f=setup();f.adapter.activate('page',configuration().selection);await settle();f.accept();const socket=f.socket();f.adapter.stop();expect(socket.sent.at(-1).type).toBe('unsubscribe');expect(socket.readyState).toBe(3);expect(f.store.size).toBe(0);expect(vi.getTimerCount()).toBe(0);await vi.advanceTimersByTimeAsync(60000);expect(f.io.socket).toHaveBeenCalledTimes(1);});
 it('Save success / Cancel allow a fresh View session; Save failure stays gated in Edit',()=>{const page={id:id(),elements:[configuration().element],revision:1} as any;const edit=beginOverviewEdit(page);expect(runtimeViewAllowed(true,edit.mode,true,configuration().selection)).toBe(false);expect(runtimeViewAllowed(true,'EDIT',true,configuration().selection)).toBe(false);expect(runtimeViewAllowed(true,finishOverviewSave(page).mode,true,configuration().selection)).toBe(true);const cancelled=cancelOverviewEdit(page);expect(cancelled.draft.elements).toEqual(page.elements);expect(runtimeViewAllowed(true,cancelled.mode,true,configuration().selection)).toBe(true);});
 it('hidden/offline are bounded and resume uses a fresh Snapshot, never Device actions',async()=>{const f=setup();f.adapter.activate('page',configuration().selection);await settle();f.accept();f.delta('cursor-0','cursor-1',sampleItem());await vi.advanceTimersByTimeAsync(200);f.adapter.pause(true);expect(f.store.getStatus().transport).toBe('Offline');expect(f.store.getItem(id())!.sample!.quality).toBe('GOOD');expect(vi.getTimerCount()).toBe(0);await vi.advanceTimersByTimeAsync(60000);expect(f.io.snapshot).toHaveBeenCalledTimes(1);f.adapter.resume();await settle();expect(f.io.snapshot).toHaveBeenCalledTimes(2);f.adapter.pause(false);expect(vi.getTimerCount()).toBe(0);});
 it('approved App remains opt-in via active prop, Provider guards ready/View, navigation fences before await',()=>{
  const page=readFileSync(new URL('../components/overview/OverviewPage.tsx',import.meta.url),'utf8');expect(page).toContain('runtimeViewAllowed(active, mode, runtimeReady, runtimeSelection)');expect(page).toContain('if (request !== runtimePageRequest.current) return');expect(page.indexOf('runtimeAdapter.stop();\n    const session = beginOverviewEdit')).toBeGreaterThan(0);
  const app=readFileSync(new URL('../App.tsx',import.meta.url),'utf8');expect(app).not.toMatch(/TagRuntimeClient|OverviewTagClientAdapter|ws\/tag-runtime/);expect(app).toContain("active={page==='Overview'}");
  const provider=readFileSync(new URL('../components/overview/OverviewRuntimeProvider.tsx',import.meta.url),'utf8');expect(provider).toContain('if (!enabled)');expect(provider).toContain('visibilitychange');expect(provider).not.toContain('key={pageId}');
 });
});
