import net from'node:net';import{EventEmitter}from'node:events';import type{DeviceConfig,DeviceRuntime}from'./types.js';
export interface Request{unitId:number;fc:number;address:number;quantity?:number;values?:number[];priority?:boolean;generation:number;workflowId?:string;nodeId?:string}
const frame=(tx:number,r:Request)=>{let p:Buffer;if(r.fc<=4){p=Buffer.alloc(5);p[0]=r.fc;p.writeUInt16BE(r.address,1);p.writeUInt16BE(r.quantity??1,3)}else if(r.fc===5||r.fc===6){p=Buffer.alloc(5);p[0]=r.fc;p.writeUInt16BE(r.address,1);p.writeUInt16BE(r.values?.[0]??0,3)}else if(r.fc===16){const values=r.values??[];p=Buffer.alloc(6+values.length*2);p[0]=16;p.writeUInt16BE(r.address,1);p.writeUInt16BE(values.length,3);p[5]=values.length*2;values.forEach((v,i)=>p.writeUInt16BE(v,6+i*2))}else throw Error('Function code not supported');const h=Buffer.alloc(7);h.writeUInt16BE(tx,0);h.writeUInt16BE(0,2);h.writeUInt16BE(p.length+1,4);h[6]=r.unitId;return Buffer.concat([h,p])};
export class DeviceConnection extends EventEmitter{socket?:net.Socket;generation=0;tx=0;queue:Array<{r:Request;ok:(b:Buffer)=>void;bad:(e:Error)=>void}>=[];active=false;manual=false;runtime:DeviceRuntime={desiredState:'disconnected',actualState:'disconnected',queueLength:0,activePollers:0,averageResponseTime:0,timeoutCount:0};constructor(public config:DeviceConfig){super()}
connect(){this.manual=false;this.runtime.desiredState='connected';this.runtime.actualState='connecting';return new Promise<void>((ok,bad)=>{const s=net.createConnection({host:this.config.host,port:this.config.port});this.socket=s;const timer=setTimeout(()=>s.destroy(Error('Connect timeout')),this.config.timeout);s.once('connect',()=>{clearTimeout(timer);this.generation++;this.runtime.actualState='connected';this.runtime.lastConnected=new Date().toISOString();this.emit('state');ok()});s.once('error',e=>{clearTimeout(timer);this.runtime.actualState='error';this.runtime.lastError=e.message;this.emit('state');bad(e)});s.once('close',()=>{this.socket=undefined;this.runtime.actualState='disconnected';this.runtime.lastDisconnected=new Date().toISOString();this.clearQueue(Error('Disconnected'));this.emit('state')})})}
disconnect(){this.manual=true;this.runtime.desiredState='disconnected';this.generation++;this.clearQueue(Error('Manual disconnect'));this.socket?.destroy();this.runtime.actualState='disconnected';this.runtime.lastDisconnected=new Date().toISOString();this.emit('state')}
clearQueue(e:Error){for(const q of this.queue)q.bad(e);this.queue=[];this.active=false;this.runtime.queueLength=0}
request(r:Omit<Request,'generation'>){return new Promise<Buffer>((ok,bad)=>{const item={r:{...r,generation:this.generation},ok,bad};r.priority?this.queue.unshift(item):this.queue.push(item);this.runtime.queueLength=this.queue.length;void this.pump()})}
private async pump():Promise<void>{if(this.active)return;const q=this.queue.shift();this.runtime.queueLength=this.queue.length;if(!q)return;if(!this.socket||this.runtime.actualState!=='connected'||q.r.generation!==this.generation){q.bad(Error('Device disconnected or stale request'));return this.pump()}this.active=true;const tx=++this.tx&0xffff;const pkt=frame(tx,q.r);const started=Date.now();this.emit('traffic',{timestamp:new Date().toISOString(),direction:'TX',deviceId:this.config.id,workflowId:q.r.workflowId,nodeId:q.r.nodeId,tx,fc:q.r.fc,address:q.r.address,quantity:q.r.quantity,encodedPayload:q.r.values?.map(v=>`0x${v.toString(16).padStart(4,'0').toUpperCase()}`).join(' '),payload:pkt.toString('hex')});try{const result=await new Promise<Buffer>((ok,bad)=>{const timer=setTimeout(()=>{this.runtime.timeoutCount++;bad(Error('Request timeout'))},this.config.timeout);const onData=(b:Buffer)=>{if(b.readUInt16BE(0)!==tx)return;clearTimeout(timer);this.socket?.off('data',onData);b[7]!&0x80?bad(Error(`Modbus exception ${b[8]}`)):ok(b)};this.socket!.on('data',onData);this.socket!.write(pkt,e=>e&&bad(e))});this.runtime.latency=Date.now()-started;q.ok(result);this.emit('traffic',{timestamp:new Date().toISOString(),direction:'RX',deviceId:this.config.id,workflowId:q.r.workflowId,nodeId:q.r.nodeId,tx,fc:q.r.fc,address:q.r.address,duration:this.runtime.latency,result:'success',payload:result.toString('hex')})}catch(e){q.bad(e as Error);this.emit('traffic',{timestamp:new Date().toISOString(),direction:'ERROR',deviceId:this.config.id,workflowId:q.r.workflowId,nodeId:q.r.nodeId,tx,fc:q.r.fc,address:q.r.address,result:'error',error:(e as Error).message})}finally{this.active=false;setTimeout(()=>void this.pump(),this.config.interRequestDelay)}}}
export const parseRead=(b:Buffer,fc:number)=>{const count=b[8]!;const data=b.subarray(9,9+count);if(fc===1||fc===2){const vals:boolean[]=[];for(let i=0;i<count*8;i++)vals.push(Boolean(data[Math.floor(i/8)]!&(1<<(i%8))));return vals}const vals:number[]=[];for(let i=0;i<count;i+=2)vals.push(data.readUInt16BE(i));return vals};
